# Generated by Django 4.1.5 on 2023-03-29 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='название')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'комната',
                'verbose_name_plural': 'комнаты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('image', models.ImageField(default='', upload_to='images/', verbose_name='изображение')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rooms', verbose_name='интерьер для')),
            ],
            options={
                'verbose_name': 'мебель',
                'verbose_name_plural': 'мебель',
                'ordering': ['-id'],
            },
        ),
    ]
